version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PGUSER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
